#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:1:00
#SBATCH --cpu-freq=2300000
#SBATCH -J job-blas
#SBATCH -o job-blas.o%j
#SBATCH -e job-blas.e%j

export MKL_NUM_THREADS=1
srun -N 1 -n 1 ./benchmark-blas
