#!/bin/bash -l
#SBATCH -C haswell
#SBATCH -p debug
#SBATCH -N 1
#SBATCH -t 00:1:00
#SBATCH --cpu-freq=2300000
#SBATCH -J job-blocked
#SBATCH -o job-blocked.o%j
#SBATCH -e job-blocked.e%j

srun -N 1 -n 1 ./benchmark-blocked
